### ISSUE TITLE
Provide ability to update parent event status before storing child event

### ISSUE THREAD

**Issue by Nikita-Smirnov-Exactpro** [th2-net/cradleapi#308]
Related PR in th2-estore https://github.com/th2-net/th2-estore/pull/121

**Comment by Nikita-Smirnov-Exactpro** [comment]
Test result on estore:5.10.0-gh-308-15842785773-2e88fa9 https://github.com/th2-net/th2-estore/pull/121
th2 schema:
```yaml
apiVersion: th2.exactpro.com/v2
kind: Th2Estore
metadata:
  name: estore
spec:
  disabled: false
  imageName: ghcr.io/th2-net/th2-estore
  imageVersion: 5.10.0-gh-308-15842785773-2e88fa9
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: >
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseContainerSupport
        -Dlog4j2.shutdownHookEnabled=false
        -Ddatastax-java-driver.advanced.connection.init-query-timeout="5 seconds"
        -Ddatastax-java-driver.basic.request.timeout="5 seconds"
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 200m
        memory: 200Mi
  cradleManager:
    prepareStorage: false
    timeout: 5000
    pageSize: 1000
    statisticsPersistenceIntervalMillis: 5000
    maxUncompressedMessageBatchSize: 64000
    updateStatusBeforeStoringEvent: true
  loggingConfig: |
    name=Th2Logger
    appender.console.type=Console
    appender.console.name=consoleLogger
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%d{dd MMM yyyy HH:mm:ss,SSS} %-6p [%-15t] %c - %m%n
    # Root logger level
    rootLogger.level=INFO
    # Root logger referring to console appender
    rootLogger.appenderRef.stdout.ref=consoleLogger
    logger.exactpro.name=com.exactpro
    logger.exactpro.level=DEBUG

```
estore log:
24 Jun 2025 07:15:01,773 DEBUG  [event-persistor-thread-1947681232] com.exactpro.cradle.CradleStorage - Storing test event gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091 asynchronously
24 Jun 2025 07:15:01,779 DEBUG  [event-persistor-thread-1947681232] com.exactpro.cradle.CradleStorage - Storing test event gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092 asynchronously
24 Jun 2025 07:15:01,779 DEBUG  [cradle-storage-0] com.exactpro.cradle.cassandra.dao.testevents.TestEventEntityUtils - Creating entity from test event 'gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091'
24 Jun 2025 07:15:01,781 DEBUG  [event-persistor-thread-1947681232] com.exactpro.cradle.CradleStorage - Updating parents of test event gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092 asynchronously
24 Jun 2025 07:15:01,782 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Parents of test event gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092 have been updated asynchronously
24 Jun 2025 07:15:01,782 DEBUG  [event-persistor-thread-1947681232] com.exactpro.cradle.CradleStorage - Storing test event gh_308:gh-308-scope:20250624071501673265000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c093 asynchronously
24 Jun 2025 07:15:01,782 DEBUG  [cradle-storage-0] com.exactpro.cradle.cassandra.dao.testevents.TestEventEntityUtils - Creating entity from test event 'gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092'
24 Jun 2025 07:15:01,782 DEBUG  [event-persistor-thread-1947681232] com.exactpro.cradle.CradleStorage - Updating parents of test event gh_308:gh-308-scope:20250624071501673265000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c093 asynchronously
24 Jun 2025 07:15:01,783 DEBUG  [event-persistor-thread-1947681232] com.exactpro.cradle.CradleStorage - Getting test event gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092 asynchronously
24 Jun 2025 07:15:01,852 DEBUG  [cradle-storage-0] com.exactpro.th2.estore.EventPersistor - Stored batch id 'gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091' parent id 'null'
24 Jun 2025 07:15:01,854 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Test event gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092 from page gh_308:2025-06-24T00\:00\:00Z:auto-page-1750723200000 got asynchronously
24 Jun 2025 07:15:01,854 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Test event gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091 has been stored asynchronously
24 Jun 2025 07:15:01,854 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Test event gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092 has been stored asynchronously
24 Jun 2025 07:15:01,855 DEBUG  [s0-io-1        ] com.exactpro.th2.estore.EventPersistor - Stored batch id 'gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092' parent id 'gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091'
24 Jun 2025 07:15:01,856 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Getting test event gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091 asynchronously
24 Jun 2025 07:15:01,860 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Test event gh_308:gh-308-scope:20250624071501463309000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c091 from page gh_308:2025-06-24T00\:00\:00Z:auto-page-1750723200000 got asynchronously
24 Jun 2025 07:15:01,862 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Parents of test event gh_308:gh-308-scope:20250624071501673265000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c093 have been updated asynchronously
24 Jun 2025 07:15:01,862 DEBUG  [cradle-storage-0] com.exactpro.cradle.cassandra.dao.testevents.TestEventEntityUtils - Creating entity from test event 'gh_308:gh-308-scope:20250624071501673265000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c093'
24 Jun 2025 07:15:01,865 DEBUG  [cradle-storage-0] com.exactpro.th2.estore.EventPersistor - Stored batch id 'gh_308:gh-308-scope:20250624071501673265000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c093' parent id 'gh_308:gh-308-scope:20250624071501670501000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c092'
24 Jun 2025 07:15:01,866 DEBUG  [cradle-storage-0] com.exactpro.cradle.CradleStorage - Test event gh_308:gh-308-scope:20250624071501673265000:f048e4a3-50ca-11f0-a6a2-ff4b38f12c093 has been stored asynchronously
